name: boot_app
description: "A app for Boot."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  animations: ^2.0.11
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  http: ^1.5.0
  logging: ^1.2.0
  material_symbols_icons: ^4.2858.1
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
